# Site Settings
title: TechWisdomByAjinkya | Just a tech blog!
email: ajinkyabapat12@gmail.com
description: What is an ocean but a multitude of drops.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://ajinkyabapat.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: TechWisdomByAjinkya
user_description: DevOps Guy.
disqus_username: 'https-ajinkyabapat-github-io'

# Social Media
# Remove the item if you don't need it
github_username: AjinkyaBapat
facebook_username: iamajinkyabapat
twitter_username: ajinkyab12
instagram_username: instagram_username
linkedin_username: ajinkyabapat
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: ajinkyabapat.me
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
